<?php

/**
 * Implements hook_page_attachments().
 *
 * Adds Dynoblock javascript and css to the page.
 */
function dynoblock_page_attachments(array &$page) {
  if (\Drupal::currentUser()->hasPermission('use dynoblocks')) {
    $page['#attached']['library'][] = 'dynoblock/edit';

   // $configs = variable_get('dynoblock', array());
    $configs['load_ui'] = TRUE;
    $configs['dir_uri'] = '/' . drupal_get_path('module', 'dynoblock');
  }
  else {
    $configs = array('load_ui' => FALSE);
  }
  $page['#attached']['library'][] = 'dynoblock/core';

  // Add configurable JS.
  $configs['ui_scroll'] = isset($configs['ui_scroll']) && $configs['ui_scroll'] === FALSE ? FALSE : TRUE;
  $page['#attached']['drupalSettings']['dynoblock']['core'] = $configs;
}


/**
 * Implements hook_theme().
 */
function dynoblock_theme($existing, $type, $theme, $path) {
  $themes = array(
    'dynoblock_tabledrag' => array(
      'render element' => 'element',
    ),
    'dynoblock_image_thumbnail' => array(
      'render element' => 'element',
    ),
  );
  return $themes;
}

/**
 * Formats uploaded image thumbnail display.
 * @param $element
 */
function theme_dynoblock_image_thumbnail($variables) {
  $element = $variables['element'];
  $output = '';
  $output .= '<div class="image-widget form-managed-file input-group clearfix">';
  if ($element['fid']['#value'] != 0) {
    // Replace default image style with thumbnail format.
    $element['filename']['#markup'] = '<div class="form-control"><span class="file">';
    $element['filename']['#markup'] .= theme('image_style', array('style_name' => 'thumbnail', 'path' => $element['#file']->uri, 'getsize' => FALSE));
    $file_url = file_create_url($element['#file']->uri);
    $element['filename']['#markup'] .= l($element['#file']->filename, $file_url) . '</span></div>';
    if (isset($element['remove_button'])) {
      $element['remove_button']['#prefix'] = '<span class="input-group-btn">';
      $element['remove_button']['#sufffix'] = '</span';
    }
  }

  // The remove button is already taken care of by rendering the rest of the form.
  $output .= drupal_render_children($element);
  $output .= '</div>';

  return $output;
}


function theme_dynoblock_tabledrag($vars) {
  $element = $vars['element'];
  drupal_add_tabledrag('widget-table-sort', 'order', 'sibling', 'item-row-weight');
  $header = array(
    'items' => t('Items'),
    'weight' => t('Weight')
  );
  $rows = array();
  foreach (element_children($element) as $key) {
    if (is_numeric($key)) {
      $row = array();
      $row['data'] = array();
      $row['data'][] = render($element[$key]);
      $row['class'] = array('draggable');
      $weight = array(
        '#type' => 'textfield',
        '#title' => t('Weight'),
        '#size' => 3,
        '#maxlength' => 3,
        '#attributes' => array('class' => array('item-row-weight')),
      );
      $row['data'][] = render($weight);
      $rows[] = $row;
    }
  }
  $output = '<div id="' . $element['#attributes']['id'] . '" class="widget-field-groups">';
  $output .= theme('table', array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array('id' => 'widget-table-sort'),
    ));
  $output .= render($element['add_another']);
  $output .= '</div>';
  return $output;
}

function dynoblock_ajax_load($type, $id) {
  $result = array('html' => NULL, 'type' => $type, 'id' => $id, 'commands' => NULL);
  if ($id && $type && !empty($_POST['data'])) {
    switch ($type) {
      case 'blocks':
        // Get the Dynblock and its renderable html.
        $blocks = DynoBlocks::renderDynoBlocks($id);
        $result['html'] = render($blocks);
        // Get the ajax commands. These can consist of js
        // files needing loaded or js settings being added..
        $commands = ajax_render(array());
        _dynoblocks_get_commands($_POST['data'], $commands);
        $result['commands'] = $commands;
        break;
    }
  }
  print drupal_json_encode($result);
}

/**
 * implments hook_dynoblock_themes
 */
function dynoblock_dynoblock_themes() {
  return array(
    'dynoblocks' => array(
      'id' => 'dynoblocks',
      'label' => 'DynoBlocks',
      'description_short' => 'Contains miscellaneous blocks.',
      'module' => 'dynoblock',
      'path' => 'themes/dynoblocks',
    ),
  );
}


function dynoblock_selector_widgets() {
  module_load_include('inc', 'dynoblock', 'includes/widgetSelector');
  $modal = new DynoblockWidgetModal();
  $modal->init();
  print drupal_json_encode(array(
      'html' => render($modal->modal),
      'sections' => $modal->build(),
      'widgets' => $modal->widgets,
      'themes' => $modal->themes,
      'default_active' => $modal->default_active,
    ));
}


/**
 * implments hook_form()
 */
function dynoblock_form($form = array(), &$form_state, $widget_form) {
  if (!empty($form_state['rebuild']) && !empty($form_state['input']['widget'])) {
    $handler = _dynoblock_find_form_handler($form_state['input']['widget']);
    $widget = DynoBLocks::getWidget($form_state['input']['widget']);
    if ($handler && $widget) {
      $handler->rebuild = TRUE;
      $handler->form = array();
      $handler->init()->build($form_state);
      DynoBlockForms::buildWidgetForm($widget, $handler, $form_state);
      DynoBlockForms::buildThemeSelection($widget, $handler, $form_state);
      $widget_form = array_replace($widget_form, $handler->form);
      $form_state['widget'] = $widget;
    }
  }
  $form = $widget_form;
  return $widget_form;
}


/**
 * Default Dynoblocks core ajax callback handler
 */
function dynoblock_core_form_ajax_callback($form, &$form_state) {
  switch ($form_state['triggering_element']['#ajax']['type']) {
    case 'add':
      array_pop($form_state['triggering_element']['#array_parents']);
      $element = drupal_array_get_nested_value($form, $form_state['triggering_element']['#array_parents']);
      return $element;
      break;
    case 'remove':
      $parents = array();
      foreach ($form_state['triggering_element']['#parents'] as $parent) {
        $parents[] = $parent;
        if ($parent == $form_state['triggering_element']['#ajax']['widget']) {
          break;
        }
      }
      $element = drupal_array_get_nested_value($form, $parents);
      return $element;
      break;
  }
}

/**
 * Default Dynoblocks core ajax callback handler
 */
function dynoblock_widget_settings_callback($form, &$form_state) {
  array_pop($form_state['triggering_element']['#array_parents']);
  array_pop($form_state['triggering_element']['#array_parents']);
  $element = drupal_array_get_nested_value($form, $form_state['triggering_element']['#array_parents']);
  return $element;

}

/**
 * Default Dynoblocks core ajax submit
 */
function dynoblock_core_form_ajax_submit($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
  $type = $form_state['triggering_element']['#attributes']['#type'];
  $widget = $form_state['input']['widget'];
  switch ($type) {
  case 'remove':
    array_pop($form_state['triggering_element']['#array_parents']);
    $num_of_parents = count($form_state['triggering_element']['#array_parents']);
    if ($num_of_parents > 3) {
      $parents = array_slice($form_state['triggering_element']['#array_parents'], 0, ($num_of_parents - 3));
    }
    else {
      $parents = array($form_state['triggering_element']['#array_parents'][0]);
    }
    $form_state['triggering_element']['#array_parents'] = $parents;
    $element = &drupal_array_get_nested_value($form_state['input'], $parents);
    $delta = $form_state['triggering_element']['#ajax']['delta'];
    if (is_array($element)) {
      unset($element[$delta]);
    }
    $element = array_values($element);
    break;
  case 'add':
    array_pop($form_state['triggering_element']['#array_parents']);
    $element = &drupal_array_get_nested_value($form_state['input'], $form_state['triggering_element']['#array_parents']);
    if (is_array($element)) {
      $element[] = array();
    }
    break;
  }
}

function dynoblock_form_ajax_callback($form, &$form_state) {
  $widget = $form_state['input']['widget'];
  $widget = _dynoblock_find_form_handler($widget);
  $trigger = $form_state['triggering_element'];
  if ($widget) {
    if (!empty($trigger['#ajax']['type']) && $trigger['#ajax']['type'] == 'widget_theme') {
      $new_parents = array();
      foreach ($trigger['#array_parents'] as $delta => $parent) {
        $new_parents[$delta] = $parent;
        if ($parent === 'theme_overview') {
          break;
        }
      }
      return drupal_array_get_nested_value($form, $new_parents);
    }
    elseif (!empty($trigger['#ajax']['type']) && $trigger['#ajax']['type'] == 'sub_item_theme') {
      array_pop($trigger['#array_parents']);
      array_pop($trigger['#array_parents']);
      array_pop($trigger['#array_parents']);
      $element = drupal_array_get_nested_value($form, $trigger['#array_parents']);
      return $element;
    }
    else {
      $result = $widget->ajaxCallback($form, $form_state);
      if (!empty($result['return_element'])) {
        return $result['return_element'];
      }
      elseif (!empty($result['commands'])) {
          print ajax_render($result['commands']);
          drupal_exit();
        }
    }
  }
}

function dynoblock_form_ajax_submit($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
  $widget = $form_state['input']['widget'];
  $widget = _dynoblock_find_form_handler($widget);
  if ($widget) {
    $widget->ajaxSubmit($form, $form_state);
  }
}


function dynoblock_field_widget_ajax_callback($form, &$form_state) {
  if (!empty($form_state['triggering_element']['#ajax']['handler'])) {
    $handler = new $form_state['triggering_element']['#ajax']['handler']($form_state);
    return $handler->onAjax($form, $form_state);
    //$handler->onAjax($form, $form_state);
  }
}

function _dynoblock_add_token_support() {
  $token['container'] = array(
    '#type' => 'container',
    '#weight' => 100,
    '#attributes' => array(
      'class' => array('dyno-token-tree'),
    ),
  );
  $token['container']['tokens'] = array(
    '#type' => 'fieldset',
    '#title' => t('Tokens'),
    '#collapsed' => TRUE,
    '#collapsible' => TRUE,
  );
  $token['container']['tokens']['tree'] = array(
    '#theme' => 'token_tree',
    '#token_types' => array('webmem_primary', 'webmem_household', 'webmem_membership', 'webmem_options'),
    '#global_types' => FALSE,
    '#click_insert' => FALSE,
  );
  return $token;
}


function dynoblock_condition_callback() {
  $condition = _dynoblock_condition_form();
  print drupal_json_encode(render($condition));
}

function _dynoblock_condition_form($values = array()) {
  $condition['conditions'] = array(
    '#type' => 'container',
    '#weight' => 98,
    '#attributes' => array(
      'class' => array('dyno-condition'),
    ),
  );
  $condition['conditions']['label'] = array(
    '#type' => 'markup',
    '#markup' => '<label>Conditions</label>',
  );
  $condition['conditions']['description'] = array(
    '#type' => 'markup',
    '#markup' => '<p>Enter a conditional that needs to return true for a this block to be displayed. If no conditionals are added, this block will display by default.</p>',
  );
  $condition['conditions']['condition_token'] = array(
    '#type' => 'textfield',
    '#title' => t('Token'),
    '#description' => t('Token for conditional.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#name' => 'condition_token',
    '#value' => isset($values['condition_token']) ? $values['condition_token'] : '',
  );

  $condition['conditions']['operators'] = array(
    '#type' => 'select',
    '#title' => t('Operator'),
    '#description' => t('The description appears usually below the item.'),
    '#options' => array(
      '==' => '==',
      '===' => '===',
      '!=' => '!=',
      '!==' => '!==',
      '<' => '<',
      '>' => '>',
      '<=' => '<=',
      '>=' => '>=',
    ),
    '#default_value' => -1,
    '#name' => 'condition_operator',
    '#value' => !empty($values['condition_operator']) ? $values['condition_operator'] : '',
  );
  $condition['conditions']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Token value'),
    '#size' => 20,
    '#maxlength' => 255,
    '#name' => 'condition_value',
    '#value' => isset($values['condition_value']) ? $values['condition_value'] : '',
  );
  return $condition;
}


function _dynoblock_weight_form($values = array()) {
  $form['weight'] = array(
    '#type' => 'container',
    '#weight' => 97,
    '#attributes' => array(
      'class' => array('dyno-weight'),
    ),
  );
  $form['weight']['weight'] = array(
    '#type' => 'textfield',
    '#title' => t('Weight'),
    '#description' => t('The title you enter here appears on the page.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#value' => isset($values['weight']) ? $values['weight'] : 0,
  );
  return $form;
}

function dynoblock_update_block($rid, $bid) {
  $result = FALSE;
  if ($block = DynoBlocksDb::getBlock($rid, $bid)) {
    foreach ($_POST as $key => $value) {
      $block[$key] = $value;
    }
    $record = array(
      'rid' => $rid,
      'bid' => $bid,
      'data' => serialize($block)
    );
    $result = DynoBlocksDb::update($record);
  }
  print drupal_json_encode(array('result' => $result));
}


function dynoblock_save_block($method) {
  // Check that this is either an edit or new save.
  // If new save, make sure bid does not already exist.
  $output = array('saved' => FALSE);
  if (!empty($_POST['rid'])
    && !empty($_POST['bid'])
    && ($method == 'edit'
    || ($method == 'new' && !DynoBlocksDb::getBlock($_POST['rid'], $_POST['bid'])))) {
    $form = _dynoblock_find_form_handler(!empty($_POST['widget']) ? $_POST['widget'] : NULL);
    if ($form) {
      $form->id = $_POST['widget'];
      $form->formSubmit($_POST);
      $record = array(
        "rid" => $_POST['rid'],
        "bid" => $_POST['bid'],
        "data" => serialize($_POST),
        'weight' => NULL,
        'conditions' => serialize(array(
            'condition_token' => !empty($_POST['condition_token']) ? !empty($_POST['condition_token']) : NULL,
            'condition_operator' => !empty($_POST['condition_operator']) ? !empty($_POST['condition_operator']) : NULL,
            'condition_value' => !empty($_POST['condition_value']) ? !empty($_POST['condition_value']) : NULL,
          ))
      );
      if ($method == 'edit') {
        $action = DynoBlocksDb::update($record);
      }
      else {
        $action = DynoBlocksDb::save($record);
      }
      if ($action) {
        $layout = _dynoblock_find_layout_handler($_POST['widget']);
        if ($layout) {
          $html = $layout->init($_POST)->preRender($_POST);
          // Call theme preRender so it can modify final output.
          $widget = DynoBLocks::getWidget($_POST['widget']);
          if (!empty($widget['parent_theme']['handler'])) {
            $theme_settings = !empty($_POST['global_theme_settings']) ? $_POST['global_theme_settings'] : array();
            $widget['parent_theme']['handler']->preRender($widget, $_POST, $html, $theme_settings);
          }
          $html = render($html);
          if ($method == 'new') {
            $html = DynoBlocks::renderNewBlock($_POST, $html);
          }
          else {
            $html = DynoBlocks::wrapEditBlock($html);
          }
          $output = array(
            'saved' => TRUE,
            'bid' => $_POST['bid'],
            'rid' => $_POST['rid'],
            'handler' => $_POST['widget'],
            'block' => $html,
          );
        }
      }
    }

    // If this region is attatched to a node, add the node
    // to be re-indexed in search_api.
    // # TODO: make config to toggle this on and off.
    if (module_exists('search_api') && !empty($_POST['nid'])) {
      search_api_track_item_change('node', array($_POST['nid']));
    }
  }
  print drupal_json_encode($output);
}



function dynoblock_block_edit($rid, $bid, $nid) {
  return DynoBlockForms::editForm($rid, $bid, $nid);
}


function dynoblock_block_remove($rid, $bid) {
  $db = new DynoBlocksDb();
  $removed = DynoBlocksDb::remove($rid, $bid);
  print drupal_json_encode(array('removed' => $removed));
}


function _dynoblock_find_form_handler($widget) {
  $core = \Drupal::service('dynoblock.core');
  $widgets = $core->loadWidgets();
  if (array_key_exists($widget, $widgets)) {
    $form = $widgets[$widget];
    $theme = $core->getTheme($form['properties']['theme']);
    if (module_load_include('inc', $form['module'], $theme['path'] . '/' . $form['properties']['dir'] . '/' . $form['form']['file'])) {
      return $form = new $form['form']['handler']();
    }
  }
}

function _dynoblock_find_layout_handler($widget) {
  $core = \Drupal::service('dynoblock.core');
  $widgets = $core->loadWidgets();
  if (array_key_exists($widget, $widgets)) {
    $layout = $widgets[$widget];
    $id = $layout['id'];
    $theme = $core->getTheme($layout['properties']['theme']);
    if (module_load_include('inc', $layout['module'], $theme['path'] . '/' . $layout['properties']['dir'] . '/' . $layout['form']['file'])) {
      if ($path = _dynoblock_find_layout_path($layout['id'])) {
        $layout = new $layout['layout']['handler']();
        $layout->directory = $path;
        $layout->id = $id;
        return $layout;
      }
      else {
        watchdog('dynoblock', "cannot find path for widget $widget. Make sure the widgets title, id and handler paths are correct.", array(), WATCHDOG_DEBUG);
      }
    }
  }
}

function _dynoblock_find_layout_path($widget) {
  $core = \Drupal::service('dynoblock.core');
  $widgets = $core->loadWidgets();
  if (array_key_exists($widget, $widgets)) {
    $widget = $widgets[$widget];
    $theme = $core->getTheme($widget['properties']['theme']);
    $path = $widget['layout']['file'];
    $dirs = explode('/', $path);
    if (count($dirs) > 1) {
      array_pop($dirs);
      $path = implode('/', $dirs);
    }
    return $theme['full_path'] . '/' . $path;
  }

}


function dynoblock_generate_form($type, $rid, $nid) {
  return DynoBlockForms::generateForm($type, $rid, $nid);
}


function _dynoblocks_get_commands($data, &$commands) {
  $files = array();
  $commands = array();
/*
  $exclude = array(
    'js' => array(
      'sites/all/modules/custom/dynoblock/js/dynoblock.js',
      '//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js',
    ),
    'css' => array(),
  );
*/
  foreach (array('css', 'js') as $type) {
    // It is highly suspicious if $_POST['ajax_page_state'][$type] is empty,
    // since the base page ought to have at least one JS file and one CSS file
    // loaded. It probably indicates an error, and rather than making the page
    // reload all of the files, instead we return no new files.
    if (empty($data['ajax_page_state'][$type])) {
      $items[$type] = array();
    }
    else {
      $function = 'drupal_add_' . $type;
      $items[$type] = $function();
      drupal_alter($type, $items[$type]);
      // @todo Inline CSS and JS items are indexed numerically. These can't be
      //   reliably diffed with array_diff_key(), since the number can change
      //   due to factors unrelated to the inline content, so for now, we strip
      //   the inline items from Ajax responses, and can add support for them
      //   when drupal_add_css() and drupal_add_js() are changed to use a hash
      //   of the inline content as the array key.
      foreach ($items[$type] as $key => $item) {
        if (is_numeric($key)) {
          unset($items[$type][$key]);
        }
      }
      foreach ($items[$type] as $key => $f_data) {
        //if (((is_array($data['ajax_page_state'][$type]) && !array_key_exists($key, $data['ajax_page_state'][$type])) || $type == 'js') && !in_array($key, $exclude[$type])) {
        if (!array_key_exists($key, $data['ajax_page_state'][$type])) {
          $files[$type][$key] = $f_data;
        }
      }
    }
  }


  // Render the HTML to load these files, and add AJAX commands to insert this
  // HTML in the page. We pass TRUE as the $skip_alter argument to prevent the
  // data from being altered again, as we already altered it above. Settings are
  // handled separately, afterwards.
  if (isset($files['js']['settings'])) {
    unset($files['js']['settings']);
  }
  if (!empty($files['css'])) {
    $styles = drupal_get_css($files['css'], TRUE);
  }
  $scripts_footer = drupal_get_js('footer', $files['js'], TRUE);
  $scripts_header = drupal_get_js('header', $files['js'], TRUE);

  $extra_commands = array();
  if (!empty($styles)) {
    $extra_commands[] = ajax_command_add_css($styles);
  }
  if (!empty($scripts_header)) {
    $extra_commands[] = ajax_command_prepend('head', $scripts_header);
  }
  if (!empty($scripts_footer)) {
    $extra_commands[] = ajax_command_append('body', $scripts_footer);
  }
  if (!empty($extra_commands)) {
    $commands = array_merge($extra_commands, $commands);
  }

  // Now add a command to merge changes and additions to Drupal.settings.
  $scripts = drupal_add_js();
  if (!empty($scripts['settings'])) {
    $settings = $scripts['settings'];
    array_unshift($commands, ajax_command_settings(drupal_array_merge_deep_array($settings['data']), TRUE));
  }


  return $files;

}
