<?php

/**
 * @file
 * Contains dcb_extras.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dcb_extras_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dcb_extras module.
    case 'help.page.dcb_extras':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Additional field types and components not included in DCB core') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dcb_extras_theme() {
  return [
    'dcb_extras' => [
      'render element' => 'children',
    ],
  ];
}
