dcb.dcb_component_type.*:
  type: config_entity
  label: 'DCB Component type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    view_modes:
      type: sequence
      sequence:
        type: string